spring.application.name=TimingNote

# DB 연결 설정
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

# 드라이버 설정
spring.datasource.driver-class-name=org.postgresql.Driver

# (선택) JPA 사용 시 테이블 자동 생성 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
